### PR TITLE
feature/#905-Add_the_option_to_run_Auto_Terms_for_different_statuses

### PR DESCRIPTION
**Pull request by ojopaul**
@stevejburge @olatechpro , i've added the input and also done the validation. Will continue on code implementation next week as i'm done with this week allocated time while working on it and decided to push what i've done so far 

screenshot

### CODE REVIEW

**Comment by stevejburge** [comment]
@ojopaul Thanks. That looks like a good approach.

Thanks for your good work in this first week

**Comment by ojopaul** [comment]
> @ojopaul Thanks. That looks like a good approach.
> 
> Thanks for your good work in this first week

You're welcome and thank you.

**Comment by ojopaul** [comment]
@stevejburge @olatechpro I've completed work on this and ready for check

**Comment by stevejburge** [comment]
@ojopaul Great, thanks. Do you feel confident creating a testable package?

Do you need some instructions from @olatechpro?

**Comment by ojopaul** [comment]
> @ojopaul Great, thanks. Do you feel confident creating a testable package?
> 
> Do you need some instructions from @olatechpro?

What's testable package ?

**Comment by stevejburge** [comment]
@ojopaul A version of the plugin with pull requests merged.

With that, users can test the new features

**Comment by ojopaul** [comment]
> @ojopaul A version of the plugin with pull requests merged.
> 
> With that, users can test the new features

All the pull request i made are on clean development version as instructed by @olatechpro .

To create a test version of all, i'll need to merge them. So, are you asking me to merge all of them together ?

Also, i'm still trying to figure out the issue https://github.com/TaxoPress/TaxoPress/issues/1051 to complete the work here

**Comment by stevejburge** [comment]
Yes, please @ojopaul 

When #1051 is done, let's merge them and then test

**Comment by ojopaul** [comment]
> Yes, please @ojopaul
> 
> When #1051 is done, let's merge them and then test

Okay, i'm unable to see the error as the class exist. May later request @olatechpro to have a look on it if not successful on it

**Comment by stevejburge** [comment]
@ojopaul OK, let's proceed without #1051 for now

**Comment by ojopaul** [comment]
@stevejburge I've combined all the pull request and here's the file

[TaxoPress.zip](https://github.com/TaxoPress/TaxoPress/files/7540906/TaxoPress.zip)

**Comment by stevejburge** [comment]
Awesome, thanks. I'll get to testing this

**Comment by stevejburge** [comment]
@ojopaul 

Sorry, tested on two local sites and both threw these errors on install:

`Warning: require_once(/www/kinsta/public/november-8/wp-content/plugins/TaxoPress/vendor/publishpress/wordpress-version-notices/includes.php): Failed to open stream: No such file or directory in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php on line 14`

`Fatal error: Uncaught Error: Failed opening required '/www/kinsta/public/november-8/wp-content/plugins/TaxoPress/vendor/publishpress/wordpress-version-notices/includes.php' (include_path='.:/usr/share/php') in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php:14 Stack trace: #0 /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/simple-tags.php(114): PublishPress\Taxopress\TaxopressCoreAdmin->__construct() #1 /www/kinsta/public/november-8/wp-includes/class-wp-hook.php(303): init_free_simple_tags() #2 /www/kinsta/public/november-8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #3 /www/kinsta/public/november-8/wp-includes/plugin.php(470): WP_Hook->do_action() #4 /www/kinsta/public/november-8/wp-settings.php(441): do_action() #5 /www/kinsta/public/november-8/wp-config.php(81): require_once('...') #6 /www/kinsta/public/november-8/wp-load.php(50): require_once('...') #7 /www/kinsta/public/november-8/wp-admin/admin.php(34): require_once('...') #8 /www/kinsta/public/november-8/wp-admin/plugins.php(10): require_once('...') #9 {main} thrown in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php on line 14`

`Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/kinsta/public/november-8/wp-includes/functions.php on line 5663`

`Notice: is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/kinsta/public/november-8/wp-includes/functions.php on line 5663`

**Comment by ojopaul** [comment]
> @ojopaul
> 
> Sorry, tested on two local sites and both threw these errors on install:
> 
> `Warning: require_once(/www/kinsta/public/november-8/wp-content/plugins/TaxoPress/vendor/publishpress/wordpress-version-notices/includes.php): Failed to open stream: No such file or directory in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php on line 14`
> 
> `Fatal error: Uncaught Error: Failed opening required '/www/kinsta/public/november-8/wp-content/plugins/TaxoPress/vendor/publishpress/wordpress-version-notices/includes.php' (include_path='.:/usr/share/php') in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php:14 Stack trace: #0 /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/simple-tags.php(114): PublishPress\Taxopress\TaxopressCoreAdmin->__construct() #1 /www/kinsta/public/november-8/wp-includes/class-wp-hook.php(303): init_free_simple_tags() #2 /www/kinsta/public/november-8/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #3 /www/kinsta/public/november-8/wp-includes/plugin.php(470): WP_Hook->do_action() #4 /www/kinsta/public/november-8/wp-settings.php(441): do_action() #5 /www/kinsta/public/november-8/wp-config.php(81): require_once('...') #6 /www/kinsta/public/november-8/wp-load.php(50): require_once('...') #7 /www/kinsta/public/november-8/wp-admin/admin.php(34): require_once('...') #8 /www/kinsta/public/november-8/wp-admin/plugins.php(10): require_once('...') #9 {main} thrown in /www/kinsta/public/november-8/wp-content/plugins/TaxoPress/includes-core/TaxopressCoreAdmin.php on line 14`
> 
> `Notice: is_embed was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/kinsta/public/november-8/wp-includes/functions.php on line 5663`
> 
> `Notice: is_search was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.0.) in /www/kinsta/public/november-8/wp-includes/functions.php on line 5663`

Check this 
[simple-tags.zip](https://github.com/TaxoPress/TaxoPress/files/7549649/simple-tags.zip)

**Pull request merged**
