### PR TITLE
use select2 search for term filters

### PR DESCRIPTION
**Pull request by Deji98**
## Description
Added select2 search box to wordpress post screen for terms filtering

## Applicable issues
#2294 
## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Comment by ojopaul** [comment]
@Deji98 Have you tested this feature and it's working? I enabled all these taxonomies but none of them has select2 for loading terms dynamically and all terms are been loaded on page load?

missing

**Review by ojopaul — CHANGES_REQUESTED** [review]
@Deji98 Kindly acknowledge the fixes when you're done by re-request review and comment so I can confirm again

**Comment by Deji98** [comment]
> @Deji98 Kindly acknowledge the fixes when you're done by re-request review and comment so I can confirm again

@ojopaul I made some changes, please check again

**Review by ojopaul — CHANGES_REQUESTED** [review]
@Deji98 Here's what I see. Is that what you did, if not, can you enable like 3 taxonomies and show me your screenshot?

**Comment by ojopaul** [comment]
@Deji98 Here's what I see. Is that what you did, if not, can you enable like 3 taxonomies and show me your screenshot as there's no difference from what I see before and now as all terms are still loaded using normal select on page load?

screen

**Comment by Deji98** [comment]
Hi @ojopaul Sorry for the issues, I've pushed new updates now that added select2 to the existing filter instead of new field.

Kindly re-review again.

**Review by ojopaul — APPROVED** [review]

**Pull request merged**
