### PR TITLE
Fix/2313 automatically display related posts in selected post types 

### PR DESCRIPTION
**Pull request by Deji98**
## Description
Set related posts to automatically display in post or pages whenever either post types are selected

## Applicable issues
#2313
## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Review by ojopaul — CHANGES_REQUESTED** [review]
@Deji98 Both your pull request and issue should match what you're committing.  Right now, your pull request and issue title doesn't match the commits

**Comment by Deji98** [comment]
> @Deji98 Both your pull request and issue should match what you're committing. Right now, your pull request and issue title doesn't match the commits.
> 
> If the issue you're fixing changes, either open new issue that match the issue you're trying to fix or update existing issue to match the changes. Same for pull request, either close it and reopen new one or update the pull request description and title.

@ojopaul I have updated the pull request now

**Review by ojopaul — CHANGES_REQUESTED** [review]
@Deji98 Most of your changes are considering only posts and pages hardcoding these. What happen to custom post type?

When dealing with post types, we expect all post types to be consider and not just posts and pages same way we expect all taxonomies when dealing with taxonomies and not just categories and tags.

Also, I don't see any logic changes to the embedded feature other than form and table display?

**Comment by Deji98** [comment]
Hi @ojopaul I've updated the pull request to make sure related post automatically show for all selected post type and completely remove embedded field.

Kindly re review.

Thanks

**Pull request closed without merging**
