### PR TITLE
Removing View Taxonomy button and Registration Key

### PR DESCRIPTION
**Pull request by jonnaametin**
Issue link: https://github.com/TaxoPress/TaxoPress/issues/1389

### CODE REVIEW

**Comment by ojopaul** [comment]
Hello @jonnaametin Thanks for the PR.

Can you removing the code completely instead of code comment?

**Comment by jonnaametin** [comment]
Hi @ojopaul, please review my latest commit. Thank you!

**Comment by ojopaul** [comment]
All good now @jonnaametin. One more thing, can you add the issue link to the PR description so i can link it?

**Comment by jonnaametin** [comment]
Hi @ojopaul, I already added the link in the description

**Comment by ojopaul** [comment]
Hello @jonnaametin, click the 3 dots highlighted in the below screenshot and then click edit to add the issue link to the PR description.

Untitled


Note, it should be added to description and not title.

Your next PR will be more easier as i've added template which you'll only fill when creating PR

**Comment by jonnaametin** [comment]
Hi @ojopaul, done updating the description with the issue link.

**Review by ojopaul — APPROVED** [review]
All good now @jonnaametin

**Pull request merged**
